### ISSUE TITLE
Variable names not minified.

### ISSUE THREAD

**Issue by austinjames314** [Rene-Sackers/StormworksLuaExtract#1]
Most of my code for stormworks seems to be variable names. This minifier is great, but I'm not getting much compression, because it's not touching the variable names. Here's an example of minified code:
`ClutchRPM=200;IdleRPM=150;MinimumKPH=55;SpdSetPointChannel=1;SpdProcVarChannel=2;SpdKpChannel=3;SpdKiChannel=4;SpdKiMaxChannel=5;`
I was expecting that to rename the variables so that it'd look more like:
`a=200;b=150;c=55;d=1;e=2;f=3;g=4;h=5;` and so on.

Is it possible to make this improvement?

**Comment by austinjames314** [comment]
OK, so I discovered that it doesn't like global variables for some reason. (Which is weird when the language makes all variables global by default).

As a result I've experimented with multiple declaration of all the variables to make them local, in order to  enable the minifier to function. It doesn't make for particularly maintainable code however. Am I missing something here?

[minifier optimised lua file](https://github.com/austinjames314/Stormworks-scripts/blob/master/Scripts/BoatController/propulsionPIDs.lua)

**Comment by Rene-Sackers** [comment]
The issue is that the minifier is a generic piece of code, not specifically tailored to Stormworks, it can't minify global variables because it doesn't know if they're being used in external files. I've been working on also minifying global variables, will probably be in the next update ;)

**Comment by austinjames314** [comment]
While I'm asking for the sky - what are the chances that the strings used to access tables can be minified?:
e.g.
`local table1 = {}`
`table1.variable1 = 1`
`table1.variable2 = 2`
into:
`local a={}a.b=1;a.c=2`
instead of the current:
`local a={}a.variable1=1;a.variable2=2`

**Comment by Rene-Sackers** [comment]
Sorry for the late reply, either way I'll basically have to write my own minifier from the ground up to make any of this possible. The one I've used currently is extremely hard to understand and modify.  
Haven't had the time recently, gotta get into it at some point and spend a few days on it.

**Comment by austinjames314** [comment]
Yeah I get that, that's fair enough. I suspected it was like that, so added that request about table access strings, in case you do write your own at some point.
