### ISSUE TITLE
Linux/Proton (su)port?

### ISSUE THREAD

**Issue by joha4270** [Rene-Sackers/StormworksLuaExtract#4]
Hi

After a bit of fiddling, I managed to get StormworksLuaExtract run on Linux and interact with Stormworks running on Steam Proton. 
Assuming code quality, would a patch adding such support be likely to be accepted?

Possible pain points:
* `PublishSingleFile`: `true` -> `false`
```
-               <PublishSingleFile>true</PublishSingleFile>
-               <RuntimeIdentifier>win-x64</RuntimeIdentifier>
+               <PublishSingleFile>false</PublishSingleFile>
+               <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
```
 * Proton `%AppData%` does not have a predictable location and instead requires parsing `Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".steam", "Steam", "config", "libraryfolders.vdf"))` to find saved vehicles programmatically.

**Comment by Rene-Sackers** [comment]
Sorry, I missed this issue! Not used to getting those on my repos :)

Yeah, if you also configure a second action to build for proton, that'd be fine. Potentially, you could set the `PublishSingleFile` property while calling `dotnet publish` only for the proton build.
As for the path, I don't have much experience with Linux/proton/Stormworks on Linux, is that 100% consistently the path the vehicles are stored in? Or will we need a command line argument or configuration so users can edit it if need be?

Thanks!

**Comment by joha4270** [comment]
> Potentially, you could set the `PublishSingleFile` property while calling `dotnet publish` only for the proton build.   

I'll take a look, but my csproj-fu is not as strong as it has been.

> is that 100% consistently the path the vehicles are stored in?

The trouble is that there is no consistent path. Proton creates a windows file system in a steam library, but a user can have as many of those as they have disks, and they can place them in arbitrary locations. The path I mentioned above is a merely a list of steam libraries, but have to be parsed. That one is, as far as I know, in a consistent path, but my sample size is me.

**Comment by Rene-Sackers** [comment]
Closing this issue. If you are still interested and want to make a PR to support using it on Linux/Proton, feel free to do so.
